// ── Shared India hierarchical location data ──────────────────
// Used by: Marketplace filter, Register address step, AddEquipment location step
// Structure: { State: { District: [taluka1, taluka2, ...] } }

export const INDIA_LOCATION = {
    'Andhra Pradesh': {
        'Visakhapatnam': ['Visakhapatnam (City)', 'Bheemunipatnam', 'Anakapalle', 'Paderu', 'Narsipatnam'],
        'Krishna': ['Vijayawada', 'Machilipatnam', 'Gudivada', 'Nuzvid', 'Tiruvuru'],
        'Guntur': ['Guntur', 'Tenali', 'Narasaraopet', 'Palnadu', 'Sattenapalle'],
        'East Godavari': ['Kakinada', 'Rajahmundry', 'Amalapuram', 'Peddapuram', 'Samalkot'],
        'West Godavari': ['Eluru', 'Bhimavaram', 'Narsapuram', 'Palacole', 'Tanuku'],
        'Kurnool': ['Kurnool', 'Nandyal', 'Atmakur', 'Alur', 'Pattikonda'],
        'Chittoor': ['Chittoor', 'Tirupati', 'Madanapalle', 'Palamaner', 'Srikalahasti'],
    },
    'Arunachal Pradesh': {
        'East Kameng': ['Seppa', 'Bana', 'Chanya', 'Pipu'],
        'Papum Pare': ['Itanagar', 'Naharlagun', 'Nirjuli', 'Banderdewa'],
    },
    'Assam': {
        'Kamrup Metro': ['Guwahati', 'Dispur', 'Azara', 'Sonapur', 'Hajo'],
        'Kamrup': ['Rangia', 'Palashbari', 'Chhaygaon', 'Rampur'],
        'Dibrugarh': ['Dibrugarh', 'Moran', 'Naharkatia', 'Duliajan', 'Tingilagarh'],
        'Jorhat': ['Jorhat', 'Titabor', 'Mariani', 'Teok'],
        'Cachar': ['Silchar', 'Sonai', 'Lakhipur', 'Udharbond'],
        'Nagaon': ['Nagaon', 'Raha', 'Lumding', 'Doboka'],
    },
    'Bihar': {
        'Patna': ['Patna City', 'Danapur', 'Fatuha', 'Bakhtiyarpur', 'Masaurhi', 'Phulwari', 'Bikram'],
        'Gaya': ['Gaya', 'Bodh Gaya', 'Sherghati', 'Wazirganj', 'Atri', 'Tekari'],
        'Muzaffarpur': ['Muzaffarpur', 'Kanti', 'Motipur', 'Bochaha', 'Sakra'],
        'Bhagalpur': ['Bhagalpur', 'Kahalgaon', 'Naugachhia', 'Bihpur'],
        'Darbhanga': ['Darbhanga', 'Benipur', 'Biraul', 'Hayaghat'],
        'Saran': ['Sonepur', 'Chhapra', 'Parsa', 'Maker'],
    },
    'Chhattisgarh': {
        'Raipur': ['Raipur', 'Abhanpur', 'Arang', 'Dharsiwa', 'Tilda-Neura'],
        'Bilaspur': ['Bilaspur', 'Masturi', 'Takhatpur', 'Beltara', 'Kota'],
        'Durg': ['Durg', 'Bhilai', 'Patan', 'Dhamdha'],
        'Rajnandgaon': ['Rajnandgaon', 'Dongargaon', 'Manpur', 'Chhuriya'],
    },
    'Delhi': {
        'Central Delhi': ['Connaught Place', 'Karol Bagh', 'Paharganj'],
        'South Delhi': ['Hauz Khas', 'Greater Kailash', 'Lajpat Nagar', 'Saket', 'Mehrauli'],
        'North Delhi': ['Civil Lines', 'Burari', 'Alipur', 'Narela'],
        'West Delhi': ['Punjabi Bagh', 'Tilak Nagar', 'Uttam Nagar', 'Janakpuri'],
        'East Delhi': ['Vivek Vihar', 'Preet Vihar', 'Patparganj', 'Mayur Vihar'],
    },
    'Goa': {
        'North Goa': ['Panaji', 'Mapusa', 'Calangute', 'Candolim', 'Pernem', 'Bicholim'],
        'South Goa': ['Margao', 'Vasco da Gama', 'Ponda', 'Quepem', 'Sanvordem'],
    },
    'Gujarat': {
        'Ahmedabad': ['Ahmedabad City', 'Daskroi', 'Detroj-Rampura', 'Dholka', 'Sanand', 'Viramgam', 'Bavla'],
        'Surat': ['Surat City', 'Bardoli', 'Mandvi', 'Olpad', 'Palsana', 'Mahuva'],
        'Vadodara': ['Vadodara City', 'Waghodiya', 'Dabhoi', 'Padra', 'Karjan', 'Savli'],
        'Rajkot': ['Rajkot City', 'Jetpur', 'Gondal', 'Upleta', 'Jasdan', 'Kotda Sangani'],
        'Anand': ['Anand', 'Petlad', 'Umreth', 'Borsad', 'Khambhat'],
        'Bharuch': ['Bharuch', 'Ankleshwar', 'Jhagadia', 'Hansot', 'Vagra'],
        'Gandhinagar': ['Gandhinagar', 'Dehgam', 'Mansa', 'Kalol'],
        'Navsari': ['Navsari', 'Gandevi', 'Vansda', 'Chikhli', 'Jalalpore'],
    },
    'Haryana': {
        'Gurugram': ['Gurugram', 'Farukhnagar', 'Pataudi', 'Sohna', 'Badshahpur'],
        'Faridabad': ['Faridabad', 'Ballabhgarh', 'Tigaon', 'Badkhal'],
        'Hisar': ['Hisar', 'Hansi', 'Barwala', 'Narnaund', 'Uklana', 'Adampur'],
        'Ambala': ['Ambala City', 'Ambala Cantonment', 'Barara', 'Naraingarh', 'Mullana'],
        'Kurukshetra': ['Thanesar', 'Shahabad', 'Pehowa', 'Ladwa', 'Babain'],
        'Rohtak': ['Rohtak', 'Sampla', 'Kalanaur', 'Meham'],
        'Sonipat': ['Sonipat', 'Gohana', 'Kharkhoda', 'Rai'],
        'Panipat': ['Panipat', 'Samalkha', 'Israna', 'Madlauda'],
    },
    'Himachal Pradesh': {
        'Shimla': ['Shimla', 'Rampur', 'Rohru', 'Chopal', 'Theog', 'Jubbal'],
        'Kangra': ['Kangra', 'Dharamsala', 'Palampur', 'Nurpur', 'Baijnath', 'Dehra'],
        'Mandi': ['Mandi', 'Sundanagar', 'Jogindernagar', 'Ner Chowk'],
        'Kullu': ['Kullu', 'Banjar', 'Manali', 'Anni'],
    },
    'Jharkhand': {
        'Ranchi': ['Ranchi', 'Bundu', 'Tamar', 'Angara', 'Kanke'],
        'Dhanbad': ['Dhanbad', 'Topchanchi', 'Baghmara', 'Tundi', 'Govindpur'],
        'East Singhbhum': ['Dhalbhum', 'Ghatsila', 'Boram', 'Baharagora'],
        'Bokaro': ['Bokaro', 'Chas', 'Chandankiyari', 'Gomia'],
    },
    'Karnataka': {
        'Bengaluru Urban': ['Bengaluru', 'Anekal', 'Bengaluru South', 'Bengaluru North', 'Dasarahalli'],
        'Mysuru': ['Mysuru', 'Hunsur', 'Nanjangud', 'T Narasipura', 'H D Kote', 'Periyapatna'],
        'Belagavi': ['Belagavi', 'Gokak', 'Ramdurg', 'Bailhongal', 'Athani', 'Chikodi'],
        'Kalaburagi': ['Kalaburagi', 'Afzalpur', 'Sedam', 'Chittapur', 'Jewargi'],
        'Dakshina Kannada': ['Mangaluru', 'Belthangady', 'Kadaba', 'Sullya', 'Puttur'],
        'Hassan': ['Hassan', 'Belur', 'Holenarasipura', 'Channarayapatna', 'Sakleshpur'],
        'Shivamogga': ['Shivamogga', 'Bhadravathi', 'Sagar', 'Tirthahalli', 'Shikaripura'],
    },
    'Kerala': {
        'Thiruvananthapuram': ['Thiruvananthapuram', 'Nedumangad', 'Varkala', 'Neyyattinkara', 'Chirayinkeezhu'],
        'Ernakulam': ['Ernakulam', 'Kothamangalam', 'Muvattupuzha', 'Paravur', 'Aluva'],
        'Kozhikode': ['Kozhikode', 'Vatakara', 'Koduvally', 'Koyilandy', 'Quilandy'],
        'Thrissur': ['Thrissur', 'Kodungallur', 'Chalakudy', 'Kunnamkulam', 'Guruvayur'],
        'Malappuram': ['Malappuram', 'Tirur', 'Manjeri', 'Ponnani', 'Perinthalmanna'],
        'Palakkad': ['Palakkad', 'Ottapalam', 'Mannarkkad', 'Chittur', 'Alathur'],
        'Kollam': ['Kollam', 'Karunagappally', 'Kottarakkara', 'Chavara', 'Kadakkal'],
    },
    'Madhya Pradesh': {
        'Indore': ['Indore', 'Depalpur', 'Mhow', 'Sanwer', 'Hatod'],
        'Bhopal': ['Bhopal', 'Berasia', 'Huzur', 'Phanda'],
        'Jabalpur': ['Jabalpur', 'Patan', 'Sihora', 'Bargi', 'Panagar'],
        'Gwalior': ['Gwalior', 'Bhind', 'Morena', 'Shivpuri', 'Guna'],
        'Ujjain': ['Ujjain', 'Nagda', 'Khachrod', 'Barnagar', 'Mahidpur'],
        'Rewa': ['Rewa', 'Teonthar', 'Hanumana', 'Gurh'],
        'Sagar': ['Sagar', 'Banda', 'Khurai', 'Rahatgarh'],
    },
    'Maharashtra': {
        'Nashik': ['Nashik', 'Sinnar', 'Igatpuri', 'Dindori', 'Niphad', 'Yeola', 'Surgana', 'Peint', 'Trimbakeshwar', 'Malegaon', 'Deola', 'Nandgaon', 'Chandwad', 'Baglan', 'Kalwan'],
        'Pune': ['Pune City', 'Haveli', 'Mulshi', 'Maval', 'Bhor', 'Velhe', 'Junnar', 'Ambegaon', 'Khed', 'Shirur', 'Daund', 'Indapur', 'Baramati', 'Purandar'],
        'Mumbai City': ['Kurla', 'Andheri', 'Borivali', 'Goregaon', 'Malad', 'Kandivali', 'Dahisar', 'Chembur', 'Mankhurd', 'Ghatkopar', 'Bhandup', 'Mulund'],
        'Mumbai Suburban': ['Andheri', 'Borivali', 'Kandivali', 'Malad', 'Goregaon', 'Jogeshwari', 'Vile Parle', 'Santacruz', 'Bandra'],
        'Thane': ['Thane', 'Kalyan', 'Ulhasnagar', 'Bhiwandi', 'Ambarnath', 'Murbad', 'Shahapur', 'Vasai-Virar', 'Palghar'],
        'Aurangabad': ['Aurangabad', 'Paithan', 'Gangapur', 'Phulambri', 'Khuldabad', 'Kannad', 'Soegaon', 'Sillod', 'Vaijapur'],
        'Kolhapur': ['Kolhapur', 'Panhala', 'Karveer', 'Hatkanangle', 'Gadhinglaj', 'Chandgad', 'Ajra', 'Bavda', 'Radhanagari'],
        'Sangli': ['Sangli', 'Miraj', 'Kupwad', 'Walwa', 'Shirala', 'Tasgaon', 'Kavate Mahankal', 'Jat', 'Atpadi', 'Khanapur'],
        'Solapur': ['Solapur North', 'Solapur South', 'Akkalkot', 'Barshi', 'Pandharpur', 'Mangalvedhe', 'Karmala', 'Madha', 'Malshiras', 'Mohol'],
        'Ahmednagar': ['Ahmednagar', 'Karjat', 'Jamkhed', 'Kopargaon', 'Rahata', 'Sangamner', 'Akole', 'Shevgaon', 'Rahuri', 'Parner', 'Shrigonda', 'Patoda', 'Newasa'],
        'Satara': ['Satara', 'Karad', 'Wai', 'Patan', 'Mahabaleshwar', 'Javali', 'Khandala', 'Khatav', 'Koregaon', 'Man', 'Phaltan'],
        'Raigad': ['Alibag', 'Panvel', 'Pen', 'Uran', 'Karjat', 'Khalapur', 'Murud', 'Roha', 'Mahad', 'Mangaon', 'Poladpur', 'Mhasla', 'Shriwardhan', 'Tala'],
        'Dhule': ['Dhule', 'Sakri', 'Shirpur', 'Sindkheda'],
        'Nandurbar': ['Nandurbar', 'Shahada', 'Akkalkuwa', 'Akrani', 'Taloda', 'Nawapur'],
        'Jalgaon': ['Jalgaon', 'Amalner', 'Chalisgaon', 'Chopda', 'Bhusawal', 'Muktainagar', 'Erandol', 'Bhadgaon', 'Pachora', 'Yawal', 'Jamner', 'Dharangaon', 'Raver', 'Parola'],
        'Buldhana': ['Buldhana', 'Khamgaon', 'Malkapur', 'Shegaon', 'Mehkar', 'Sangrampur', 'Lonar', 'Motala', 'Nandura', 'Jalgaon-Jamod', 'Chikhli', 'Deulgaon Raja', 'Sindkhed Raja'],
        'Akola': ['Akola', 'Akot', 'Balapur', 'Murtijapur', 'Patur', 'Telhara', 'Barshitakli'],
        'Washim': ['Washim', 'Karanja', 'Manora', 'Malegaon', 'Risod', 'Mangrulpir'],
        'Amravati': ['Amravati', 'Achalpur', 'Daryapur', 'Chandur Bazar', 'Chandur Railway', 'Morshi', 'Warud', 'Anjangaon', 'Bhatkuli', 'Chikhaldara', 'Dharni', 'Nandgaon Khandeshwar'],
        'Yavatmal': ['Yavatmal', 'Umarkhed', 'Wani', 'Babhulgaon', 'Darwha', 'Ghatanji', 'Kalamb', 'Kelapur', 'Mahagaon', 'Maregaon', 'Ner', 'Pusad', 'Ralegaon', 'Zari-Jamni'],
        'Wardha': ['Wardha', 'Arvi', 'Hinganghat', 'Samudrapur', 'Deoli', 'Seloo', 'Ashti', 'Karanja'],
        'Nagpur': ['Nagpur City', 'Nagpur Rural', 'Kamptee', 'Hingna', 'Umred', 'Parseoni', 'Ramtek', 'Mouda', 'Bhiwapur', 'Katol', 'Kalmeshwar', 'Savner', 'Narkhed'],
        'Bhandara': ['Bhandara', 'Tumsar', 'Mohadi', 'Sakoli', 'Lakhani', 'Lakhandur', 'Pauni'],
        'Gondia': ['Gondia', 'Amgaon', 'Arjuni-Morgaon', 'Deori', 'Goregaon', 'Saleksa', 'Sadak-Arjuni', 'Tirora'],
        'Chandrapur': ['Chandrapur', 'Bhadravati', 'Warora', 'Rajura', 'Ballarpur', 'Gondpipri', 'Mul', 'Nagbhid', 'Pombhurna', 'Sindewahi', 'Chimur', 'Jivati', 'Korpana', 'Brahmpuri'],
        'Gadchiroli': ['Gadchiroli', 'Armori', 'Aheri', 'Bhamragad', 'Chamorshi', 'Desaiganj', 'Dhanora', 'Etapalli', 'Korchi', 'Kurkheda', 'Mulchera', 'Sironcha'],
        'Osmanabad': ['Osmanabad', 'Tuljapur', 'Lohara', 'Omerga', 'Paranda', 'Bhoom', 'Kalamb', 'Washi'],
        'Latur': ['Latur', 'Udgir', 'Nilanga', 'Deoni', 'Chakur', 'Ausa', 'Renapur', 'Ahmedpur', 'Shirur Anantpal', 'Jalkot'],
        'Nanded': ['Nanded', 'Mukhed', 'Bhokar', 'Biloli', 'Deglur', 'Dharmabad', 'Hadgaon', 'Himayatnagar', 'Kandhar', 'Kinwat', 'Loha', 'Mahoor', 'Mudkhed', 'Naigaon', 'Umri'],
        'Hingoli': ['Hingoli', 'Basmath', 'Sengaon', 'Aundha Nagnath', 'Kalamnuri'],
        'Parbhani': ['Parbhani', 'Gangakhed', 'Jintur', 'Manwath', 'Palam', 'Pathri', 'Purna', 'Selu', 'Sonpeth'],
        'Jalna': ['Jalna', 'Ambad', 'Badnapur', 'Bhokardan', 'Ghansavangi', 'Jafrabad', 'Mantha', 'Partur'],
        'Beed': ['Beed', 'Ashti', 'Ambajogai', 'Dharur', 'Georai', 'Kaij', 'Majalgaon', 'Patoda', 'Shirur Kasar', 'Wadwani'],
        'Ratnagiri': ['Ratnagiri', 'Rajapur', 'Lanja', 'Dapoli', 'Mandangad', 'Chiplun', 'Guhagar', 'Khed', 'Sangameshwar'],
        'Sindhudurg': ['Kudal', 'Kankavli', 'Malvan', 'Sawantwadi', 'Devgad', 'Dodamarg', 'Vaibhavwadi', 'Vengurla'],
        'Palghar': ['Palghar', 'Vasai', 'Dahanu', 'Talasari', 'Jawhar', 'Mokhada', 'Wada', 'Vikramgad'],
    },
    'Manipur': {
        'Imphal West': ['Imphal', 'Lamphel', 'Patsoi', 'Wangoi'],
        'Imphal East': ['Heingang', 'Jiribam', 'Keirengang', 'Lamlai'],
    },
    'Meghalaya': {
        'East Khasi Hills': ['Shillong', 'Cherrapunji', 'Pynursla', 'Mawkyrwat'],
        'West Khasi Hills': ['Nongstoin', 'Mairang', 'Ranikor'],
    },
    'Mizoram': {
        'Aizawl': ['Aizawl', 'Lunglei', 'Champhai', 'Kolasib'],
    },
    'Nagaland': {
        'Kohima': ['Kohima', 'Jotsoma', 'Phesama', 'Kigwema'],
        'Dimapur': ['Dimapur', 'Chumukedima', 'Medziphema'],
    },
    'Odisha': {
        'Khorda': ['Bhubaneswar', 'Bhubaneswar North', 'Bhubaneswar South', 'Jatni', 'Khorda', 'Balianta'],
        'Cuttack': ['Cuttack', 'Athagarh', 'Baramba', 'Banki', 'Tigiria'],
        'Puri': ['Puri', 'Nimapara', 'Kakatpur', 'Pipili', 'Brahmagiri'],
        'Ganjam': ['Berhampur', 'Chhatrapur', 'Bhanjanagar', 'Polasara', 'Aska'],
        'Sambalpur': ['Sambalpur', 'Kuchinda', 'Bamra', 'Rengali', 'Jujumura'],
        'Balasore': ['Balasore', 'Nilgiri', 'Soro', 'Basta', 'Simulia'],
    },
    'Punjab': {
        'Ludhiana': ['Ludhiana', 'Khanna', 'Raikot', 'Jagraon', 'Samrala', 'Payal'],
        'Amritsar': ['Amritsar', 'Ajnala', 'Attari', 'Baba Bakala', 'Jandiala Guru'],
        'Jalandhar': ['Jalandhar', 'Phillaur', 'Nakodar', 'Shahkot', 'Kartarpur'],
        'Patiala': ['Patiala', 'Nabha', 'Rajpura', 'Sanour'],
        'Bathinda': ['Bathinda', 'Talwandi Sabo', 'Rampura Phul', 'Nathana'],
        'Mohali (SAS Nagar)': ['Mohali', 'Kharar', 'Zirakpur', 'Derabassi', 'Dera Bassi'],
    },
    'Rajasthan': {
        'Jaipur': ['Jaipur', 'Sanganer', 'Amer', 'Chaksu', 'Bassi', 'Kotputli', 'Viratnagar', 'Shahpura'],
        'Jodhpur': ['Jodhpur', 'Phalodi', 'Osian', 'Bhopalgarh', 'Shergarh', 'Luni'],
        'Udaipur': ['Udaipur', 'Mavli', 'Vallabhnagar', 'Kherwara', 'Salumbar', 'Gogunda'],
        'Kota': ['Kota', 'Sangod', 'Itawa', 'Digod', 'Ladpura'],
        'Bikaner': ['Bikaner', 'Kolayat', 'Nokha', 'Lunkaransar', 'Bajju'],
        'Ajmer': ['Ajmer', 'Kishangarh', 'Pushkar', 'Nasirabad', 'Beawar'],
        'Alwar': ['Alwar', 'Ramgarh', 'Rajgarh', 'Kishangarhbas', 'Kathumar'],
    },
    'Sikkim': {
        'East Sikkim': ['Gangtok', 'Ranipool', 'Pakyong'],
        'West Sikkim': ['Gyalshing', 'Dentam', 'Yuksom'],
    },
    'Tamil Nadu': {
        'Chennai': ['Chennai', 'Ambattur', 'Tiruvottiyur', 'Sholinganallur', 'Perungudi'],
        'Coimbatore': ['Coimbatore', 'Pollachi', 'Mettupalayam', 'Anamalai', 'Valparai'],
        'Madurai': ['Madurai', 'Thiruppuvanam', 'Melur', 'Peraiyur', 'Usilampatti'],
        'Salem': ['Salem', 'Attur', 'Mettur', 'Omalur', 'Yercaud'],
        'Tiruchirappalli': ['Tiruchirappalli', 'Srirangam', 'Musiri', 'Manachanallur', 'Thuraiyur'],
        'Tirunelveli': ['Tirunelveli', 'Palayamkottai', 'Ambasamudram', 'Nanguneri', 'Tenkasi'],
        'Erode': ['Erode', 'Gobichettipalayam', 'Bhavani', 'Perundurai', 'Sathyamangalam'],
        'Vellore': ['Vellore', 'Arni', 'Gudiyatham', 'Katpadi', 'Arakkonam'],
    },
    'Telangana': {
        'Hyderabad': ['Hyderabad', 'Secunderabad', 'Uppal', 'LB Nagar', 'Malkajgiri'],
        'Rangareddy': ['Rangareddy', 'Chevella', 'Tandur', 'Vikarabad', 'Pargi', 'Shamshabad'],
        'Warangal (Urban)': ['Warangal', 'Hanamkonda', 'Narsampet', 'Parkal'],
        'Medchal-Malkajgiri': ['Medchal', 'Keesara', 'Ghatkesar', 'Shamirpet'],
        'Nalgonda': ['Nalgonda', 'Bhongir', 'Miryalaguda', 'Nakrekal'],
        'Karimnagar': ['Karimnagar', 'Huzurabad', 'Husnabad', 'Jagtial'],
    },
    'Tripura': {
        'West Tripura': ['Agartala', 'Majlishpur', 'Sadar', 'Jirania'],
        'Gomati': ['Udaipur', 'Amarpur', 'Karbook'],
    },
    'Uttar Pradesh': {
        'Lucknow': ['Lucknow', 'Mohanlalganj', 'Bakshi Ka Talab', 'Malihabad', 'Sarojini Nagar'],
        'Kanpur': ['Kanpur', 'Ghatampur', 'Bilhaur', 'Bhitargaon', 'Kalyanpur'],
        'Agra': ['Agra', 'Kheragarh', 'Fatehabad', 'Bah', 'Etmadpur'],
        'Varanasi': ['Varanasi', 'Pindra', 'Cholapur', 'Arajiline', 'Sewapuri'],
        'Prayagraj': ['Prayagraj', 'Phulpur', 'Soraon', 'Meja', 'Handia', 'Karchana'],
        'Mathura': ['Mathura', 'Govardhan', 'Vrindavan', 'Chhata', 'Kosi Kalan'],
        'Meerut': ['Meerut', 'Hapur', 'Modipuram', 'Daurala', 'Sardhana'],
        'Bareilly': ['Bareilly', 'Faridpur', 'Mirganj', 'Nawabganj', 'Bhojipura'],
        'Gorakhpur': ['Gorakhpur', 'Sahjanwa', 'Khajani', 'Campierganj', 'Bhathat'],
        'Aligarh': ['Aligarh', 'Koil', 'Iglas', 'Khair', 'Atrauli'],
    },
    'Uttarakhand': {
        'Dehradun': ['Dehradun', 'Rishikesh', 'Haridwar', 'Vikasnagar', 'Chakrata', 'Doiwala'],
        'Nainital': ['Nainital', 'Haldwani', 'Bhimtal', 'Ramnagar', 'Bazpur', 'Kaladhungi'],
        'Almora': ['Almora', 'Ranikhet', 'Dwarahat', 'Chaukhutiya', 'Bhikiyasain'],
        'Haridwar': ['Haridwar', 'Roorkee', 'Laksar', 'Manglaur', 'Narsan'],
    },
    'West Bengal': {
        'Kolkata': ['Kolkata', 'Jadavpur', 'Behala', 'Kasba', 'Tollygunge'],
        'Howrah': ['Howrah', 'Uluberia', 'Bally', 'Amta', 'Udaynarayanpur'],
        'Murshidabad': ['Murshidabad', 'Jiaganj', 'Berhampore', 'Domkal', 'Raninagar'],
        'Nadia': ['Krishnanagar', 'Ranaghat', 'Kalyani', 'Chakdaha', 'Shantipur'],
        'North 24 Parganas': ['Barasat', 'Basirhat', 'Habra', 'Deganga', 'Rajarhat'],
        'South 24 Parganas': ['Baruipur', 'Diamond Harbour', 'Kakdwip', 'Joynagar', 'Namkhana'],
        'Bardhaman': ['Bardhaman', 'Kalna', 'Katwa', 'Asansol', 'Durgapur'],
    },
    'Jammu & Kashmir': {
        'Jammu': ['Jammu', 'Akhnoor', 'Bishnah', 'Khour', 'Suchetgarh'],
        'Srinagar': ['Srinagar', 'Eidgah', 'Khanyar', 'Hazratbal'],
        'Anantnag': ['Anantnag', 'Bijbehara', 'Pahalgam', 'Kulgam'],
    },
    'Ladakh': {
        'Leh': ['Leh', 'Nimoo', 'Khaltsi', 'Nubra'],
        'Kargil': ['Kargil', 'Zanskar', 'Drass'],
    },
};

export const ALL_STATES = Object.keys(INDIA_LOCATION).sort();

/** Given a state, returns sorted array of district names */
export function getDistricts(state) {
    return state && INDIA_LOCATION[state] ? Object.keys(INDIA_LOCATION[state]).sort() : [];
}

/** Given a state + district, returns sorted array of talukas */
export function getTalukas(state, district) {
    return state && district && INDIA_LOCATION[state]?.[district]
        ? [...INDIA_LOCATION[state][district]].sort()
        : [];
}
